name: Upload to S3 Bucket and Notify

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli -y

    - name: Upload to S3 Bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1  # Replace with your desired AWS region
        BUCKET_NAME: lcs-product-release
        LOCAL_FILE: "./README.md"  # Replace with the relative path to your single file in the repository
        S3_OBJECT_KEY: "cheetah/embsw/dumper/"  # Specify the desired S3 object key
      run: |
        aws s3 cp $LOCAL_FILE s3://$BUCKET_NAME/$S3_OBJECT_KEY
        # Set UPLOAD_SUCCESS to 'true' if the upload was successful
        echo "UPLOAD_SUCCESS=true" >> $GITHUB_ENV
        echo "LOCAL_FILE=${{ env.LOCAL_FILE }}" >> $GITHUB_ENV
        echo "BUCKET_NAME=${{ env.BUCKET_NAME }}" >> $GITHUB_ENV
        echo "S3_OBJECT_KEY=${{ env.S3_OBJECT_KEY }}" >> $GITHUB_ENV
        
    - name: Send email notification
      run: |
        echo "The file upload to the S3 bucket was successful. File details follow:" > email_body.txt
        echo "File: $LOCAL_FILE" >> email_body.txt
        echo "S3 Bucket: $BUCKET_NAME" >> email_body.txt
        echo "File Upload Status: $UPLOAD_SUCCESS" >> email_body.txt
      env:
        LOCAL_FILE: ${{ env.LOCAL_FILE }}
        BUCKET_NAME: ${{ env.BUCKET_NAME }}
        UPLOAD_SUCCESS: "true"
    - name: Debug Environment Variables
      run: |
        echo "UPLOAD_SUCCESS: $UPLOAD_SUCCESS"
        
      env:
        UPLOAD_SUCCESS: ${{ env.UPLOAD_SUCCESS }}
      
    - name: Email notification
      if: env.UPLOAD_SUCCESS == 'true'
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.office365.com  # Replace with your SMTP server address
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        from: admin@lcscon.com  # Replace with the sender's email address
        to: kanagavel@lcscon.com  # Replace with the recipient's email address
        subject: "File Upload to S3 Successful"
        body: |
         The file upload to the S3 bucket was successful. File details follow:
          - File: ${{ env.LOCAL_FILE }}
          - S3 Bucket: ${{ env.BUCKET_NAME }}/${{env.S3_OBJECT_KEY}}
          - File Upload Status: ${{ env.UPLOAD_SUCCESS }}
